spring:
  config:
    activate:
      on-profile: local
server:
  port: 8080

histour:
  secret:
    key: ${HISTOUR_SECRET_KEY}
  token:
    expire_time:
      access: ${EXPIRE_ACCESS_TOKEN_TIME}
      refresh: ${EXPIRE_REFRESH_TOKEN_TIME}
