FROM amd64/amazoncorretto:17

WORKDIR /app

COPY ./histour-bootstrap/build/libs/histour-bootstrap-0.0.1-SNAPSHOT.jar /app/HisTour-Spring.jar

CMD ["java", "-Duser.timezone=Asia/Seoul", "-jar", "-Dspring.profiles.active=prod", "HisTour-Spring.jar"]
