FROM amd64/amazoncorretto:17

WORKDIR /app

COPY ./build/libs/HisTour-Spring-0.0.1-SNAPSHOT-plain.jar /app/HisTour-Spring.jar

CMD ["java", "-Duser.timezone=Asia/Seoul", "-jar", "-Dspring.profiles.active=prod", "HisTour-Spring.jar"]
