name: CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Download Infisical Secrets
        run: |
          curl -H "Authorization: Bearer ${{ secrets.SECRET_MANAGER_TOKEN }}" \
               "https://api.infisical.com/workspace/${{ secrets.SECRET_MANAGER_WORKSPACE_ID }}/secrets" \
               -o secrets.json
          export DB_PASSWORD=$(jq -r '.DB_PASSWORD' secrets.json)
          export DB_URL=$(jq -r '.DB_URL' secrets.json)
          export DB_USERNAME=$(jq -r '.DB_USERNAME' secrets.json)
          export HISTOUR_SECRET_KEY=$(jq -r '.HISTOUR_SECRET_KEY' secrets.json)

      - name: 빌드
        run: |
          chmod +x gradlew
          ./gradlew build -x test