name: Docker Test

on:
  push:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: SSH로 서버 접속
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RELEASE_SERVER_IP }}
          username: ${{ secrets.RELEASE_SERVER_USER }}
          key: ${{ secrets.RELEASE_SERVER_KEY }}
          script: |
            cd ~

      - name: Check Docker status
        run: |
          sudo systemctl status docker
          sudo docker --debug ps

      - name: Verify running containers
        run: |
          sudo docker ps -a
