name: Docker Test

on:
  push:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Start Docker
        run: |
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Check Docker status
        run: |
          sudo systemctl status docker
          sudo docker --debug ps

      - name: Verify running containers
        run: |
          sudo docker ps -a
